Marketplace.Website/Controllers/AdminController.cs
using Marketplace.Business;
using Marketplace.Entities.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Marketplace.Website.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        // GET: Admin/Details/5
        public ActionResult List()
        {
            var biz = new LoginBiz();
            var model = biz.List();
            return View(model);
        }

        // GET: Admin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Create
        [HttpPost]
        public ActionResult Create(LogInModel model)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Admin/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Admin/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Marketplace.Website/Controllers/CategoryController.cs
using Marketplace.Business;
using Marketplace.Entities.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Marketplace.Website.Controllers
{
    public class CategoryController : Controller
    {
        /// <summary>
        /// Listar categorias para generar el modelo que luego 
        /// se lo paso a la vista para que la muestre
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            var biz = new CategoryBiz();
            var model = biz.List();
            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

     

        [HttpPost]
        public ActionResult Create(Category model)
        {
            if (!ModelState.IsValid) // Para controlar si el modelo es válido 
                return View();

            // TODO: implementar para bitacora
            try
            {
                var biz = new CategoryBiz();
                biz.Create(model);
                return RedirectToAction("Index");// Para redireccionar al index de Categorias
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                return View(model);
            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var biz = new CategoryBiz();
            var model = biz.Get(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(Category model)
        {
            try
            {
                var biz = new CategoryBiz();
                biz.Edit(model);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                return View(model);
            }
        }
    

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var biz = new CategoryBiz();
            var model = biz.Get(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(Category model)
        {
            try
            {
                var biz = new CategoryBiz();
                biz.Delete(model);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                return View(model);
            }
        }
    }
}

Marketplace.Website/Controllers/ProductController.cs
using Marketplace.Business;
using Marketplace.Entities.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Marketplace.Website.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            var biz = new ProductBiz();
            var model = biz.List();
            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            try
            {

                var categoryBiz = new CategoryBiz();

                List<Category> categoryList = (from c in categoryBiz.List()
                                               select new Category
                                               {
                                                   Id = c.Id,
                                                   Name = c.Name
                                               }).ToList();

                List<SelectListItem> categories = categoryList.ConvertAll(c =>
                {
                    return new SelectListItem()
                    {
                        Text = c.Name.ToString(),
                        Value = c.Id.ToString(),
                        Selected = false
                    };
                });

                ViewBag.items = categories;

                return View();//Lo corte aca
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                return View();
            }
        }

        [HttpPost]
        public ActionResult Create(Product model)
        {
            if (!ModelState.IsValid) // Para controlar si el modelo es válido 
              return View();

            // TODO: implementar para bitacora
            try
            {

            var categoryBiz = new CategoryBiz();

            List<Category> categoryList = (from c in categoryBiz.List()
                                            select new Category
                                            { 
                                                Id = c.Id,
                                                Name = c.Name
                                            }).ToList();

            List<SelectListItem> categories = categoryList.ConvertAll(c =>
            {
                return new SelectListItem()
                {
                    Text = c.Name.ToString(),
                    Value = c.Id.ToString(),
                    Selected = false
                };
            });

            ViewBag.items = categories;

                //return View();//Lo corte aca

            var productBiz = new ProductBiz();
            model.LastUpdated = DateTime.Now;
            productBiz.Create(model);
                
            return RedirectToAction("Index");
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
            return View(model);
        }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var biz = new ProductBiz();
            var model = biz.Get(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(Product model)
        {
            try
            {
                var biz = new ProductBiz();
                model.LastUpdated = DateTime.Now;
                biz.Edit(model);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                return View(model);
            }
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var biz = new ProductBiz();
            var model = biz.Get(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(Product model)
        {
            try
            {
                var biz = new ProductBiz();
                biz.Delete(model);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                return View(model);
            }
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            var biz = new ProductBiz();
            var model = biz.Get(id);
            return View(model);
        }       
    }
}

Marketplace.Website/Views/Admin/Create.cshtml
@model Marketplace.Entities.Models.LogInModel

@using (Html.BeginForm()) 
{
    @*Html.AntiForgeryToken()*@
    
    <div class="form-horizontal">
        <h4>LogInModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReturnUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReturnUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReturnUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Marketplace.Website/Views/Admin/Delete.cshtml
@model Marketplace.Entities.Models.LogInModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LogInModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReturnUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReturnUrl)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @*Html.AntiForgeryToken()*@

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Marketplace.Website/Views/Admin/Edit.cshtml
@model Marketplace.Entities.Models.LogInModel

@using (Html.BeginForm())
{
    @*Html.AntiForgeryToken()*@
    
    <div class="form-horizontal">
        <h4>LogInModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReturnUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReturnUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReturnUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Marketplace.Website/Views/Admin/Index.cshtml
@* Admin page after login *@
@{
    ViewBag.Title = "Inicio de sesión";
}
<h2>Panel de Administración</h2>
<br />
<ul id="adminOption">
    <li>
        <a href=@Url.Action("Index", "Product") >Administrar Productos</a>
    </li>
    <li>
        <a href=@Url.Action("Index", "Category") >Administrar Categorias</a>
    </li>
    <li>
        <a href=@Url.Action("List", "Admin") >Administrar Usuarios</a>
    </li>
</ul>

Marketplace.Website/Views/Admin/List.cshtml
@model IEnumerable<Marketplace.Entities.Models.LogInModel>

@{
    ViewBag.Title = "List";
}

<h2>List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReturnUrl)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Password)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReturnUrl)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Eliminar", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>